### ISSUE TITLE
clim.units results in attribute error

### ISSUE THREAD

**Issue by laufers** [carpentrieslab/python-aos-lesson#13]
When working on the second episode, when I get to change the units for the precip data, I get the following error. 

AttributeError: cannot set attribute 'units' on a 'DataArray' object. Use __setitem__ style assignment (e.g., `ds['name'] = ...`) instead to assign variables.

**Comment by laufers** [comment]
I got clim.attrs['units'] = 'mm/day' to work.

**Comment by laufers** [comment]
OK, now I see that the later code does make use of the .attrs naming where you reverse the color index. 
So need to fix the typo in the previous code box. 
s

**Comment by DamienIrving** [comment]
Thanks for spotting this typo, @laufers! Much appreciated.
