### ISSUE TITLE
[JOSE]  general inconsistencies in how you refer to relative paths 

### ISSUE THREAD

**Issue by RobTheOceanographer** [carpentrieslab/python-aos-lesson#21]
There are general inconsistencies in how you refer to relative paths - sometimes `data/...` other times `.../data/...`. While most users can figure this out it would be better to go through the lessons and tidy this up

CC: openjournals/jose-reviews#37

**Comment by DamienIrving** [comment]
Thanks for spotting this error, @RobTheOceanographer.

I've gone ahead and corrected all references to the `data` directory (see https://github.com/carpentrieslab/python-aos-lesson/commit/7265c43294f1cbd8da275ca03ad8296721ed801a).
