### ISSUE TITLE
Zenodo authorization

### ISSUE THREAD

**Issue by DamienIrving** [carpentrieslab/python-aos-lesson#24]
@fmichonneau As the last step of publishing these lessons with the Journal of Open Source Education, I need to generate a DOI using Zenodo:
https://guides.github.com/activities/citable-code/

I had Zenodo send an authorization request to carpentrieslab, which I'm assuming came to you?

**Comment by fmichonneau** [comment]
I just granted zeonodo. Congrats on the publication in JOSE!
