### ISSUE TITLE
Replace FIXMEs in CONTRIBUTING.md

### ISSUE THREAD

**Issue by DamienIrving** [carpentrieslab/python-aos-lesson#27]
The CONTRIBUTING.md file still has the default information in it and needs to be updated with the specifics relating to this repository.

**Comment by eldobbins** [comment]
What do you think about adding a link to https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md#?

It's helpful but maybe not canon?

**Comment by DamienIrving** [comment]
Good idea. I've had a go at adding those links and also removing all the old content that doesn't relate specifically to the PyAOS lessons. Check out #28.
